let name ="Umamaheswari";
let sub1 = 90;
let sub2 = 97;
let sub3 = 89;
let sub4 = 95;
let sub5 = 99;
let total = sub1 + sub2 + sub3 + sub4 + sub5;
let average = total/5;
console.log("Name",name);
console.log("Total",total);
console.log("average",average);
